//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int adminId { get; set; }
        public string adminMail { get; set; }
        public string adminPassword { get; set; }
        public string adminToken { get; set; }
    }
}
