//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emlakPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int userId { get; set; }
        public string userMail { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public string token { get; set; }
        public string adminIslem { get; set; }
        public string adminMessge { get; set; }
    }
}
